#!/bin/sh
set -e

case "$1" in
    remove)
        if systemctl is-active sour.is-profile.service; then
                systemctl stop sour.is-profile.service
        fi
    ;;

    purge)
        if systemctl is-enabled sour.is-profile.service; then
                systemctl disable sour.is-profile.service
        fi
    ;;
esac

exit 0


